[requirements]
packages = ["curl", "xz-utils", "libsm6", "libxext6", "libxrender1", "libxi6", "libxkbcommon0", "libgl1", "libegl1", "libxcursor1", "libxfixes3", "libxinerama1", "libxrandr2", "libegl-mesa0"]

[inputs]
type = "range_continuous"

[[download.files]]
url  = "https://drive.usercontent.google.com/download?id=1L9tkite4WGG3QM8e7MvkTyhYZjHNm_aW&export=download&authuser=0&confirm=t&uuid=7fef5a01-aa7a-4364-93a3-a5333aaeec22&at=AGN2oQ1bYX9PppsVukRcczL4cQW0%3A1773345498431"
dest = "blender-4.1-splash.blend"

[[download.files]]
url  = "https://drive.usercontent.google.com/download?id=1TzsxCi8Xvie4PeOJ4U3Xg0Yuch1mWPkk&export=download&authuser=0&confirm=t&uuid=16c81afd-5c70-4499-9861-a815b0189eff&at=AGN2oQ0MGrB85ijfaOJY6cf_-SoD:1773870247065"
dest = "blender-5.1.0-linux-x64.tar.xz"
 
[inputs.range_continuous]
start = 1
end   = 250   
step  = 1
 
[runner]
command    = "bash render.sh"
arg_start  = "--start"
arg_end    = "--end"
workdir    = "."
extra_args = ""
 
[outputs]
dir              = "outputs"
filename_pattern = "frames_{start}_{end}.tar.gz"
